image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

stages:
  - build
  - test
  
variables:
  build_config: "Release"
  
build:
  stage: build
  script:
    - "dotnet build . --configuration $build_config"

test:
  stage: test
  script:
    - "dotnet test ."