image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

stages:
  - build
  - test
  - docker build and push
  
variables:
  build_config: "Release"
  
build:
  stage: build
  script:
    - "dotnet build . --configuration $build_config"

test:
  stage: test
  script:
    - "dotnet test . --configuration $build_config"

docker build and push:
  stage: docker build and push
  script:
    - docker build -t registry.gitlab.com/gkama/gtk-nlp-finance-vanguard .
    - docker push registry.gitlab.com/gkama/gtk-nlp-finance-vanguard