image: docker:stable

stages:
  - docker build
  - registry push
  - docker push
  
variables:
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE:latest
  
docker build:
  stage: docker build
  script:
    - docker build -t .

registry push:
  stage: registry push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/gkama/gtk-nlp-finance-vanguard:latest .
    - docker push $CI_REGISTRY/gkama/gtk-nlp-finance-vanguard:latest
  only:
    - master

docker push:
  stage: docker push
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push .
  only:
    - master