image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

stages:
  - build
  - test
  - registry build and push
  
variables:
  BUILD_CONFIG: "Release"
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE:latest
  
build:
  stage: build
  script:
    - "dotnet build . --configuration $BUILD_CONFIG"

test:
  stage: test
  script:
    - "dotnet test . --configuration $BUILD_CONFIG"

registry build and push:
  stage: registry build and push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $REGISTRY_IMAGE .
    - docker push $REGISTRY_IMAGE